FROM node:18.17.1-bookworm

ENV NODE_ENV=development

WORKDIR /misskey

RUN apt-get update
RUN apt-get install -y build-essential \
                       autoconf \
                       automake \
                       file \
                       g++ \
                       gcc \
                       libtool \
                       nasm \
                       pkg-config \
                       python \
                       zlib1g-dev \
                       ffmpeg \
                       wget \
                       mecab \
                       mecab-ipadic-utf8 \
                       tini \
                       wget

RUN corepack enable pnpm

CMD ["/misskey/docker-entrypoint.sh"]
