FROM node:20.12.2-alpine3.19 AS base

ENV NODE_ENV=production
ENV COREPACK_DEFAULT_TO_LATEST=0

WORKDIR /misskey

FROM base AS builder

RUN apk add --no-cache \
    autoconf \
    automake \
    file \
    g++ \
    gcc \
    libc-dev \
    libtool \
    make \
    nasm \
    pkgconfig \
    python3 \
    zlib-dev \
    git

COPY package.json pnpm-lock.yaml ./

RUN corepack enable pnpm

RUN pnpm i --frozen-lockfile

COPY . ./

RUN pnpm build

FROM base AS runner

ENV COREPACK_DEFAULT_TO_LATEST=0

RUN apk add --no-cache \
    ffmpeg \
    tini

RUN corepack enable pnpm

ENTRYPOINT ["/sbin/tini", "--"]

COPY --from=builder /misskey/node_modules ./node_modules
COPY --from=builder /misskey/built ./built
COPY . ./

CMD ["pnpm", "start"]
