name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: atsu1125/misskey_web
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_to_registry_alpine:
    name: Push Docker image to Docker Hub and GitHub Container Registry for alpine
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: atsu1125/misskey_web
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-alpine
          push: true
          tags: atsu1125/misskey_web:alpine
          labels: alpine
      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-alpine
          push: true
          tags: ghcr.io/atsu1125/misskey:alpine


  push_to_registry_fedora:
    name: Push Docker image to Docker Hub and GitHub Container Registry for fedora
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: atsu1125/misskey_web
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-fedora
          push: true
          tags: atsu1125/misskey_web:fedora
          labels: fedora
      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-fedora
          push: true
          tags: ghcr.io/atsu1125/misskey:fedora

  push_to_registry_ubuntu:
    name: Push Docker image to Docker Hub and GitHub Container Registry for ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: atsu1125/misskey_web
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-ubuntu
          push: true
          tags: atsu1125/misskey_web:ubuntu
          labels: ubuntu
      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-ubuntu
          push: true
          tags: ghcr.io/atsu1125/misskey:ubuntu
