name: MacOS CI
on: [push]

jobs:
  build_and_test:
    runs-on: macos-11

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    services:
      mongo:
        image: mongo:4.4-bionic
        ports:
          - 57010:27017
      redis:
        image: redis:4.0-alpine
        ports:
          - 56310:6379

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - run: git diff --exit-code yarn.lock
    - name: Copy Configure
      run: cp test/test.yml .config/
    - name: Build
      run: yarn build
    - name: Check webpack process
      run: ls built/meta.json
    - name: Test
      run: yarn test
