name: Node.js CI

on: [push]

env:
  COREPACK_DEFAULT_TO_LATEST: 0

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    services:
      mongo:
        image: mongo:6-jammy
        ports:
          - 57010:27017
      redis:
        image: redis:bookworm
        ports:
          - 56310:6379

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3.0.0
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: node cli/diag-environment.js
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y --no-install-recommends ffmpeg
    - run: pnpm i --frozen-lockfile
    - run: pnpm build
    - run: ls built/meta.json
    - run: cp test/test.yml .config/
    - run: pnpm test
